"use client";
import { ThreeDMarquee } from "@/app/components/ui/3d-marquee";

export default function Marquee() {
  const images = [
    "/Marquee_Folder.svg",
    // "https://assets.aceternity.com/animated-modal.png",
    "/Marquee_BIO.svg",
    // "https://assets.aceternity.com/animated-testimonials.webp",
    "/Marquee_Folder.svg",
    // "https://assets.aceternity.com/cloudinary_bkp/Tooltip_luwy44.png",
    // "https://assets.aceternity.com/github-globe.png",
    // "https://assets.aceternity.com/glare-card.png",
    // "https://assets.aceternity.com/layout-grid.png",
    "/Marquee_BIO.svg",
    "/MATHS_TUTORING.svg",
    "/public/Marquee_TrueFounders_Dark.svg",
    "/AI_PSEUDOCODE.svg",
    // "https://assets.aceternity.com/flip-text.png",
    "/Marquee_Folder.svg",
    "/Marquee_NumerixAI.svg",
    "/Marquee_Folder.svg",
    // "https://assets.aceternity.com/hero-highlight.png",
    "/Marquee_Folder.svg",
    // "https://assets.aceternity.com/carousel.webp",
    // "https://assets.aceternity.com/placeholders-and-vanish-input.png",
    "/Marquee_BIO.svg",
    "/Marquee_BIO.svg",
    // "https://assets.aceternity.com/shooting-stars-and-stars-background.png",
    "/Marquee_Folder.svg",
    // "https://assets.aceternity.com/signup-form.png",
    // "https://assets.aceternity.com/cloudinary_bkp/stars_sxle3d.png",
    // "https://assets.aceternity.com/spotlight-new.webp",
    // "https://assets.aceternity.com/cloudinary_bkp/Spotlight_ar5jpr.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Parallax_Scroll_pzlatw_anfkh7.png",
    // "https://assets.aceternity.com/tabs.png",
    "/Marquee_BIO.svg",
    "/Marquee_BIO.svg",
    "/Marquee_BIO.svg",
    "/Marquee_BIO.svg",
    "/Marquee_NumerixAI.svg",
    "/Marquee_NumerixAI.svg",
    "/Marquee_NumerixAI.svg",
    "https://assets.aceternity.com/cloudinary_bkp/Tracing_Beam_npujte.png",
    "https://assets.aceternity.com/cloudinary_bkp/typewriter-effect.png",
    "https://assets.aceternity.com/glowing-effect.webp",
    "https://assets.aceternity.com/hover-border-gradient.png",
    "https://assets.aceternity.com/cloudinary_bkp/Infinite_Moving_Cards_evhzur.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Lamp_hlq3ln.png",
    "/Marquee_NumerixAI.svg",
    // "https://assets.aceternity.com/macbook-scroll.png",
    "/Marquee_GithubFinderProfiles.svg",
    "https://assets.aceternity.com/cloudinary_bkp/Meteors_fye3ys.png",
    "https://assets.aceternity.com/cloudinary_bkp/Moving_Border_yn78lv.png",
    "https://assets.aceternity.com/multi-step-loader.png",
    "https://assets.aceternity.com/vortex.png",
    "https://assets.aceternity.com/wobble-card.png",
    "https://assets.aceternity.com/world-map.webp",
  ];
  return (
    <div className="mx-auto my-10 max-w-7xl rounded-3xl bg-gray-950/5 p-2 ring-1 ring-neutral-700/10 dark:bg-neutral-800">
      <ThreeDMarquee images={images} />
    </div>
  );
}
