import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tailark Quartz pages",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main
      role="main"
      data-theme="dark"
      className="bg-background"
      style={{
        backgroundImage: `url(/BG_2.svg)`,
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",
      }}
    >
      {children}
    </main>
  );
}
